# Panilla configuration

# Do not change
configuration-version: 1.0

locale-file: en_US.yml

# Logging options
logging:
  console: false
  chat: false

# Strictness of how much you wish to enforce
#   lenient - Only prevent game-breaking things or crashes
#   average - Prevent most abusive things
#   strict  - Prevent anything non-vanilla
strictness: average

# This prevents users from creating high resolution skulls with
# a Minecraft Education account
#
# strictness must be set to average or strict
#
# See this paste: https://paste.ubuntu.com/p/SSGg6szMc4/
prevent-minecraft-education-skulls: false

# This prevents FAWE brush NBT on items. It stops users from giving
# out FAWE brush items which may trick others into accidentally WorldEdit'ing
#
# strictness must be set to average or strict
prevent-fawe-brush-nbt: false

# Whitelist NBT tags from being checked
nbt-whitelist:
#  - Enchantments   # 1.13 and up format
#  - ench           # 1.12 and below format

# You shouldn't have to touch this.
#
# If you have plugins which use an excessive amount of
# custom NBT keys, then you can raise it as high as you like.
#
# This is to prevent crash items which have an excessive
# amount of NBT keys.
max-non-minecraft-nbt-keys: 16
